spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wp2
    username: root
    password: adminpw
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create-drop

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://db:3306/wp2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: create-drop