spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wp2
    username: root
    password: adminpw
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://db:3306/wp2
    username: root
    password: adminpw
    initialize: true